#! /bin/sh

bspc config normal_border_color "#000000"
bspc config focused_border_color "#666666"
bspc config presel_feedback_color "#666666"
bspc config border_width        1
bspc config window_gap         5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config click_to_focus false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding 40
echo configuration complete

# create desktops
#bspc monitor -d {,,,,,,,}
bspc monitor -d {1,2,3,4,5,6}
