#! /bin/sh
xrandr --output Virtual1 --auto --mode 2560x1600
sxhkd &
mpd 
feh --bg-scale ~/.config/bspwm/wallpaper/shack.jpg
#compton --config ~/.config/bspwm/compton.conf -b

slack &
~/.config/bspwm/panel &

bspc config border_width        8
bspc config window_gap         40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
