#! /bin/bash
#
# Example panel for lemonbar

. ~/.config/bspwm/panel_colors

num_mon=$(bspc query -M | wc -l)

battery() {
  bat_info=$(acpi -b | awk "{print $1}")
  charge_icon=''

  BATTERY=$(echo "$bat_info" | sed 's/\([^:]*\): \([^,]*\), \([0-9]*\)%.*/\3/')
  bat_color=$GREEN2_COLOR
  bat_icon=

  if [ $BATTERY -lt 33 ]; then
    bat_icon=
    bat_color=$RED_COLOR
  elif [ $BATTERY -lt 66 ]; then
    bat_icon=
    bat_color=$YELLOW2_COLOR
  elif [ $BATTERY -lt 90 ]; then
    bat_icon=
    bat_color=$YELLOW2_COLOR
  fi

  # override icon to show charging
  if [ `echo "$bat_info" | sed 's/\([^:]*\): \([^,]*\), \([0-9]*\)%.*/\2/'` == "Charging" ]; then
    bat_icon=
  fi
  echo "%{F$bat_color}${charge_icon} ${bat_icon} $BATTERY% %{F-} "
}

load_avg() {
    current_load=$(cut -d " " -f 1 /proc/loadavg)
    load_color=$RED_COLOR
    load_icon=

    if [ `echo "$current_load < 1" | bc` -eq 1 ] ; then
      load_color=$GREEN2_COLOR
    elif [ `echo "$current_load < 2" | bc` -eq 1 ] ; then
      load_color=$YELLOW2_COLOR
    fi

    echo "%{F$load_color} $load_icon $current_load %{F-}"
}

mpd() {
  status=`mpc | grep -oP '^\[[^\]]*\]'`
  MPD_COLOR=$INACTIVE_FG
  if [ "$status" = '[playing]' ] ; then
    MPD_COLOR=$SECONDARY_FG
  fi

  # brighter means its playing
	echo "%{F$MPD_COLOR} $(mpc current)%{F-}"
}


while read -r line ; do
	case $line in
		# M*)
		#     STATUS=$(mpc current)
		#     mpd="%{F$CYAN2_COLOR}$(printf '%b' "\uf2b6") $STATUS%{F-}"
		S*)
			# clock output
			sys="%{F$SECONDARY_FG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						# wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:}  $(printf '%b' "\uf34f")  %{A}%{B-}%{F-}"
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:}  ${name}  %{A}%{B-}%{F-}"
					# [LTG]*)
					;;
					# 	# layout, state and flags
					# 	;;
					# 	wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
				esac
				shift
			done
			;;
	esac

	printf "%s\n" "%{l}${wm}  $(mpd)%{r}$(battery)$(load_avg)${sys}"
done
